name: Deploy Go Package

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'         
      - 'v[0-9]+.[0-9]+.[0-9]+-(alpha|beta|rc).[0-9]+'
  
jobs:
  deploy:
    name: Deploy to Go Proxy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Publish Go Module
        run: |
          go mod tidy
          GOPROXY=proxy.golang.org go list -m "github.com/aggregator-cloud/rooms@${{ env.VERSION }}"
        env:
          GOPROXY: "proxy.golang.org"
